repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: check-added-large-files
      - id: debug-statements
      - id: detect-private-key
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [
                                  "flake8-bandit",
                                  "flake8-bugbear",
                                  "dlint",
                                  "flake8-builtins",
                                  "flake8-functions-names",
                                  "pep8-naming",
                                  "flake8-variables-names",
                                  "hacking",
#                                  "flake8-warnings",
                                  "flake8-secure-coding-standard",
                                  "flake8-use-fstring",
                                  "flake8-use-pathlib",
                                  "flake8-pep585",
                                  "flake8-pep604",
                                  "flake8-new-union-types",
                                  "flake8-annotations",
                                  "flake8-class-attributes-order",
                                  "flake8-comprehensions",
                                  "flake8-logging-format",
                                  "flake8-print",
                                  "flake8-pytest-style",
                                  "flake8-pytest",
                                  "flake8-annotations-complexity",
                                  ]
        exclude: ^core/queries/
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.971"
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        exclude: '\S*/queries/\S*\.py'
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
       - id: isort
         args: [ "--profile", "black", "--filter-files" ]
         language_version: python3

  - repo: https://github.com/psf/black
    rev: 22.8.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.3
    hooks:
      - id: pyupgrade
        language_version: python3

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
    -   id: shellcheck

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.3.0
    hooks:
    -   id: detect-secrets
        exclude: package.lock.json
