version: '3.5'

services:

  postgres:
    image: postgres:14.2
    container_name: {{cookiecutter.container_name}}_postgres
    ports:
      - "{{cookiecutter.postgres_port}}:5432"
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - {{cookiecutter.docker_network_name}}


networks:
  {{cookiecutter.docker_network_name}}:
    driver: bridge